// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: proto/coordinator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskResponse_Action int32

const (
	TaskResponse_ACTION_UNSPECIFIED TaskResponse_Action = 0
	TaskResponse_WAIT               TaskResponse_Action = 1
	TaskResponse_EXECUTE            TaskResponse_Action = 2
	TaskResponse_SHUTDOWN           TaskResponse_Action = 3
)

// Enum value maps for TaskResponse_Action.
var (
	TaskResponse_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "WAIT",
		2: "EXECUTE",
		3: "SHUTDOWN",
	}
	TaskResponse_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"WAIT":               1,
		"EXECUTE":            2,
		"SHUTDOWN":           3,
	}
)

func (x TaskResponse_Action) Enum() *TaskResponse_Action {
	p := new(TaskResponse_Action)
	*p = x
	return p
}

func (x TaskResponse_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskResponse_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_coordinator_proto_enumTypes[0].Descriptor()
}

func (TaskResponse_Action) Type() protoreflect.EnumType {
	return &file_proto_coordinator_proto_enumTypes[0]
}

func (x TaskResponse_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskResponse_Action.Descriptor instead.
func (TaskResponse_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{3, 0}
}

type TaskResult_Status int32

const (
	TaskResult_STATUS_UNSPECIFIED TaskResult_Status = 0
	TaskResult_SUCCESS            TaskResult_Status = 1
	TaskResult_FAILED_RETRYABLE   TaskResult_Status = 2 // e.g., Network timeout, IO error
	TaskResult_FAILED_FATAL       TaskResult_Status = 3 // e.g., Malformed data, code crash
)

// Enum value maps for TaskResult_Status.
var (
	TaskResult_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "SUCCESS",
		2: "FAILED_RETRYABLE",
		3: "FAILED_FATAL",
	}
	TaskResult_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"SUCCESS":            1,
		"FAILED_RETRYABLE":   2,
		"FAILED_FATAL":       3,
	}
)

func (x TaskResult_Status) Enum() *TaskResult_Status {
	p := new(TaskResult_Status)
	*p = x
	return p
}

func (x TaskResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_coordinator_proto_enumTypes[1].Descriptor()
}

func (TaskResult_Status) Type() protoreflect.EnumType {
	return &file_proto_coordinator_proto_enumTypes[1]
}

func (x TaskResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskResult_Status.Descriptor instead.
func (TaskResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{7, 0}
}

// -------------------------------------------------------------------------
// Heartbeat Messages
// -------------------------------------------------------------------------
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{1}
}

// -------------------------------------------------------------------------
// Task Polling Messages
// -------------------------------------------------------------------------
type TaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkerId          string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	AvailableCapacity uint32                 `protobuf:"varint,2,opt,name=available_capacity,json=availableCapacity,proto3" json:"available_capacity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *TaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskRequest) GetAvailableCapacity() uint32 {
	if x != nil {
		return x.AvailableCapacity
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        TaskResponse_Action    `protobuf:"varint,1,opt,name=action,proto3,enum=worker.v1.TaskResponse_Action" json:"action,omitempty"`
	Tasks         []*TaskEntry           `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResponse) GetAction() TaskResponse_Action {
	if x != nil {
		return x.Action
	}
	return TaskResponse_ACTION_UNSPECIFIED
}

func (x *TaskResponse) GetTasks() []*TaskEntry {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TaskId    uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TaskEntry_MapTask
	//	*TaskEntry_ReduceTask
	Payload       isTaskEntry_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEntry) Reset() {
	*x = TaskEntry{}
	mi := &file_proto_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEntry) ProtoMessage() {}

func (x *TaskEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEntry.ProtoReflect.Descriptor instead.
func (*TaskEntry) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *TaskEntry) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskEntry) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskEntry) GetPayload() isTaskEntry_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskEntry) GetMapTask() *MapTask {
	if x != nil {
		if x, ok := x.Payload.(*TaskEntry_MapTask); ok {
			return x.MapTask
		}
	}
	return nil
}

func (x *TaskEntry) GetReduceTask() *ReduceTask {
	if x != nil {
		if x, ok := x.Payload.(*TaskEntry_ReduceTask); ok {
			return x.ReduceTask
		}
	}
	return nil
}

type isTaskEntry_Payload interface {
	isTaskEntry_Payload()
}

type TaskEntry_MapTask struct {
	MapTask *MapTask `protobuf:"bytes,3,opt,name=map_task,json=mapTask,proto3,oneof"`
}

type TaskEntry_ReduceTask struct {
	ReduceTask *ReduceTask `protobuf:"bytes,4,opt,name=reduce_task,json=reduceTask,proto3,oneof"`
}

func (*TaskEntry_MapTask) isTaskEntry_Payload() {}

func (*TaskEntry_ReduceTask) isTaskEntry_Payload() {}

type MapTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputFile     string                 `protobuf:"bytes,1,opt,name=input_file,json=inputFile,proto3" json:"input_file,omitempty"`
	StartOffset   uint64                 `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	Length        uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapTask) Reset() {
	*x = MapTask{}
	mi := &file_proto_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTask) ProtoMessage() {}

func (x *MapTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTask.ProtoReflect.Descriptor instead.
func (*MapTask) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *MapTask) GetInputFile() string {
	if x != nil {
		return x.InputFile
	}
	return ""
}

func (x *MapTask) GetStartOffset() uint64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *MapTask) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReduceTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   uint32                 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceTask) Reset() {
	*x = ReduceTask{}
	mi := &file_proto_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceTask) ProtoMessage() {}

func (x *ReduceTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceTask.ProtoReflect.Descriptor instead.
func (*ReduceTask) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *ReduceTask) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

// -------------------------------------------------------------------------
// Task Completion Messages
// -------------------------------------------------------------------------
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        uint64                 `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskResult_Status      `protobuf:"varint,3,opt,name=status,proto3,enum=worker.v1.TaskResult_Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OutputFiles   []string               `protobuf:"bytes,5,rep,name=output_files,json=outputFiles,proto3" json:"output_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *TaskResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskResult) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskResult) GetStatus() TaskResult_Status {
	if x != nil {
		return x.Status
	}
	return TaskResult_STATUS_UNSPECIFIED
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetOutputFiles() []string {
	if x != nil {
		return x.OutputFiles
	}
	return nil
}

var File_proto_coordinator_proto protoreflect.FileDescriptor

const file_proto_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x17proto/coordinator.proto\x12\tworker.v1\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\x13\n" +
	"\x11HeartbeatResponse\"Y\n" +
	"\vTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12-\n" +
	"\x12available_capacity\x18\x02 \x01(\rR\x11availableCapacity\"\xb9\x01\n" +
	"\fTaskResponse\x126\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1e.worker.v1.TaskResponse.ActionR\x06action\x12*\n" +
	"\x05tasks\x18\x02 \x03(\v2\x14.worker.v1.TaskEntryR\x05tasks\"E\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04WAIT\x10\x01\x12\v\n" +
	"\aEXECUTE\x10\x02\x12\f\n" +
	"\bSHUTDOWN\x10\x03\"\xb9\x01\n" +
	"\tTaskEntry\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12/\n" +
	"\bmap_task\x18\x03 \x01(\v2\x12.worker.v1.MapTaskH\x00R\amapTask\x128\n" +
	"\vreduce_task\x18\x04 \x01(\v2\x15.worker.v1.ReduceTaskH\x00R\n" +
	"reduceTaskB\t\n" +
	"\apayload\"c\n" +
	"\aMapTask\x12\x1d\n" +
	"\n" +
	"input_file\x18\x01 \x01(\tR\tinputFile\x12!\n" +
	"\fstart_offset\x18\x02 \x01(\x04R\vstartOffset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\"/\n" +
	"\n" +
	"ReduceTask\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\rR\vpartitionId\"\x97\x02\n" +
	"\n" +
	"TaskResult\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x04R\x06taskId\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.worker.v1.TaskResult.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12!\n" +
	"\foutput_files\x18\x05 \x03(\tR\voutputFiles\"U\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\x14\n" +
	"\x10FAILED_RETRYABLE\x10\x02\x12\x10\n" +
	"\fFAILED_FATAL\x10\x032\xe3\x01\n" +
	"\vCoordinator\x12N\n" +
	"\x0fRecordHeartbeat\x12\x1b.worker.v1.HeartbeatRequest\x1a\x1c.worker.v1.HeartbeatResponse\"\x00\x12>\n" +
	"\tPollTasks\x12\x16.worker.v1.TaskRequest\x1a\x17.worker.v1.TaskResponse\"\x00\x12D\n" +
	"\x10SubmitTaskResult\x12\x15.worker.v1.TaskResult\x1a\x17.worker.v1.TaskResponse\"\x00B\x1fZ\x1dgithub.com/prxssh/shard/protob\x06proto3"

var (
	file_proto_coordinator_proto_rawDescOnce sync.Once
	file_proto_coordinator_proto_rawDescData []byte
)

func file_proto_coordinator_proto_rawDescGZIP() []byte {
	file_proto_coordinator_proto_rawDescOnce.Do(func() {
		file_proto_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)))
	})
	return file_proto_coordinator_proto_rawDescData
}

var file_proto_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_coordinator_proto_goTypes = []any{
	(TaskResponse_Action)(0),  // 0: worker.v1.TaskResponse.Action
	(TaskResult_Status)(0),    // 1: worker.v1.TaskResult.Status
	(*HeartbeatRequest)(nil),  // 2: worker.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: worker.v1.HeartbeatResponse
	(*TaskRequest)(nil),       // 4: worker.v1.TaskRequest
	(*TaskResponse)(nil),      // 5: worker.v1.TaskResponse
	(*TaskEntry)(nil),         // 6: worker.v1.TaskEntry
	(*MapTask)(nil),           // 7: worker.v1.MapTask
	(*ReduceTask)(nil),        // 8: worker.v1.ReduceTask
	(*TaskResult)(nil),        // 9: worker.v1.TaskResult
}
var file_proto_coordinator_proto_depIdxs = []int32{
	0, // 0: worker.v1.TaskResponse.action:type_name -> worker.v1.TaskResponse.Action
	6, // 1: worker.v1.TaskResponse.tasks:type_name -> worker.v1.TaskEntry
	7, // 2: worker.v1.TaskEntry.map_task:type_name -> worker.v1.MapTask
	8, // 3: worker.v1.TaskEntry.reduce_task:type_name -> worker.v1.ReduceTask
	1, // 4: worker.v1.TaskResult.status:type_name -> worker.v1.TaskResult.Status
	2, // 5: worker.v1.Coordinator.RecordHeartbeat:input_type -> worker.v1.HeartbeatRequest
	4, // 6: worker.v1.Coordinator.PollTasks:input_type -> worker.v1.TaskRequest
	9, // 7: worker.v1.Coordinator.SubmitTaskResult:input_type -> worker.v1.TaskResult
	3, // 8: worker.v1.Coordinator.RecordHeartbeat:output_type -> worker.v1.HeartbeatResponse
	5, // 9: worker.v1.Coordinator.PollTasks:output_type -> worker.v1.TaskResponse
	5, // 10: worker.v1.Coordinator.SubmitTaskResult:output_type -> worker.v1.TaskResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_coordinator_proto_init() }
func file_proto_coordinator_proto_init() {
	if File_proto_coordinator_proto != nil {
		return
	}
	file_proto_coordinator_proto_msgTypes[4].OneofWrappers = []any{
		(*TaskEntry_MapTask)(nil),
		(*TaskEntry_ReduceTask)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coordinator_proto_goTypes,
		DependencyIndexes: file_proto_coordinator_proto_depIdxs,
		EnumInfos:         file_proto_coordinator_proto_enumTypes,
		MessageInfos:      file_proto_coordinator_proto_msgTypes,
	}.Build()
	File_proto_coordinator_proto = out.File
	file_proto_coordinator_proto_goTypes = nil
	file_proto_coordinator_proto_depIdxs = nil
}
