package api

// KeyValue is the fundamental data unit for Shard.
//
// It represents a single pair of data passed between the Map and Reduce
// phases. The Map function outputs a slice of these, which are then
// partitioned, sorted, and passed to the appropriate Reduce worker.
type KeyValue struct {
	Key   string
	Value string
}

// MapFunc is the signature for the user's Map function.
//
// Shard calls this function once for each input record.
//
// Arguments:
//   - key: the identifier for the input source (e.g., a filename or byte offset).
//   - value: the content to be processed (e.g., entire file content or single line).
//
// Returns:
//   - A slice of intermediate KeyValue pairs.
type MapFunc func(key string, value string) []KeyValue

// ReduceFunc is the signature for the user's Reduce function.
//
// Shard calls this function once for each unique key generated by the Map
// phase. It is guaranteed that all values associated with the `key` are
// present in the `values`.
//
// Arguments:
//   - key: the intermediate key.
//   - values: a list of all string values associated with that key.
//
// Returns:
//   - A single aggregated string result.
type ReduceFunc func(key string, values []string) string

// PartitionFunc determines which Reduce task handles a specific key.
//
// It runs on the Map worker to decide which intermediate file a KeyValue pair
// belongs to.
//
// Arguments:
//   - key: The intermediate key.
//   - nReduce: The total number of reduce tasks configured for the job.
//
// Returns:
//   - An integer between 0 and nReduce-1.
//
// If not provided in Config, Shard defaults to a hash-based partitioner:
//
//	hash(key) % nReduce
type PartitionFunc func(key string, nReduce int) int
